name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./Movie_Review_Proj --file ./Movie_Review_Proj/Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: ./Movie_Review_Proj/dist/*.whl
        retention-days: 1

  push-image:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
        path: ./Movie_Review_Proj/movie_review_model_api

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: cd bikeshare_project && docker build . -f Dockerfile -t $DOCKER_USER/movie_review_model_api:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: docker push $DOCKER_USER/movie_review_model_api

    - name: Logout to Docker hub
      run: docker logout
